weapon:SetMesh("rv", "grenade_08/rv1_lod0.mesh", 0)
weapon.ik_enable = false
weapon.hand_bind_type = "kHandNone"
weapon.name = "\202\214\192\215"
weapon.sound_name = "grenade"
weapon.skeleton = "/skeleton/grenade_08.skel"
weapon.animation_set = "grenade_08"
weapon.icon = texture("/ui/skinF/lobby/grenade_08.tga")
weapon.kill_icon = texture("/ui/weapon/grenade_01.dds")
weapon.ammo_icon = texture("/ui/ingameF/weapon_ammo_icon/grenade_08.tga")
weapon.cross_hair_icon = texture("/ui/weapon/grenade.dds")
weapon.explode_particle = "s_bow_explosion"
weapon.explode_sound = "go/impact_3d/explosion_grenade"
weapon.throw_sound_3d = "go/weapons_3d/grenade/fire"
weapon.sound_name = "grenade"
