module("Text", package.seeall)

function CreatEnumTable(tbl, index)
  if type(tbl) == "table" then
    local enumtbl = {}
    local enumindex = index or 0
    for i, v in ipairs(tbl) do
      enumtbl[v] = enumindex + i - 1
    end
    return enumtbl
  end
end

GameMode = {
  kTeam = "\229\155\162\233\152\159\231\171\158\230\138\128",
  kExplode = "\231\136\134\231\160\180",
  kBanner = "\232\189\176\231\130\184",
  kZombie = "\229\188\130\229\189\162",
  kTeamDead = GetUTF8Text("button_common_Team_Death_Match"),
  kTreasure = GetUTF8Text("button_common_Capture_the_Treasure"),
  kContention = GetUTF8Text("button_common_King_of_the_Hill"),
  kHero = "\232\139\177\233\155\132",
  kOccupy = GetUTF8Text("button_common_Domination"),
  kSnatch = GetUTF8Text("button_common_Capture_the_Treasure"),
  kNovice = "\232\174\173\231\187\131"
}
ServerError = {"kErrorNone"}
ServerErrorProxy = {
  "kErrorProxyStart",
  "kErrorProxyEnterChannel",
  "kErrorProxyChannelFull",
  "kErrorProxyChannelConnect",
  "kErrorProxyChannelConnectClientCount",
  "kErrorProxyChannelConnectAlreadyIn",
  "kErrorProxyMatchingFailed",
  "kErrorProxyCancelMatchingFailed",
  "kErrorProxyMatchingFailedServerOffline",
  "kErrorProxyTeamMatchingNotLeader",
  "kErrorProxyTeamMatchingCancelNotLeader",
  "kErrorProxyTeamCreate",
  "kErrorProxyTeamCreateAlreadyHaveTeam",
  "kErrorProxyTeamCreateLevelError",
  "kErrorProxyTeamCreateNoGameMode",
  "kErrorProxyTeamInvite",
  "kErrorProxyTeamInviteSelf",
  "kErrorProxyTeamInviteAlreadyInOtherTeam",
  "kErrorProxyTeamInviteAlreadyInTeam",
  "kErrorProxyTeamInviteClientError",
  "kErrorProxyTeamInviteNotTeamLeader",
  "kErrorProxyTeamInviteTeamFull",
  "kErrorProxyTeamInviteMatching",
  "kErrorProxyTeamInviteGameing",
  "kErrorProxyTeamInviteLevelError",
  "kErrorProxyTeamJoin",
  "kErrorProxyTeamJoinLeaderError",
  "kErrorProxyTeamJoinLeaderIdError",
  "kErrorProxyTeamJoinMemberError",
  "kErrorProxyTeamJoinTeamFull",
  "kErrorProxyTeamJoinTeamNotExist",
  "kErrorProxyTeamLeave",
  "kErrorProxyTeamLeaveTeamNotExist",
  "kErrorProxyTeamLeaveTeamNotInTeam",
  "kErrorProxyTeamChangeLeader",
  "kErrorProxyTeamChangeLeaderNoTeam",
  "kErrorProxyTeamChangeLeaderNotLeader",
  "kErrorProxyTeamChangeLeaderNotInTeam",
  "kErrorProxyTeamChangeGameMode",
  "kErrorProxyTeamChangeGameModeNoTeam",
  "kErrorProxyTeamChangeGameModeNotLeader",
  "kErrorProxyTeamChangeGameModeNoMode",
  "kErrorProxyTeamKick",
  "kErrorProxyTeamKickNoTeam",
  "kErrorProxyTeamKickNotLeader",
  "kErrorProxyTeamKickNotInTeam",
  "kErrorProxyTeamKickInGame",
  "kErrorProxyRoomInvite",
  "kErrorProxyRoomInviteSelf",
  "kErrorProxyRoomInviteClientError",
  "kErrorProxyRoomInviteClientNotInLobby",
  "kErrorProxyRoomInviteClientInGame",
  "kErrorProxyRoomInviteNotInRoom",
  "kErrorProxyTeamInviteRefused",
  "kErrorProxyRoomNameInvalid",
  "kErrorProxyTeamCall",
  "kErrorProxyGuildInvite",
  "kErrorProxyGuildInviteClientError",
  "kErrorProxyGuildInviteSelf",
  "kErrorProxyGuildInviteClientNotInLobby",
  "kErrorProxyGuildInviteClientInGame"
}
ServerErrorChannel = {
  "kErrorChannelStart",
  "kErrorChannelRoomCreate",
  "kErrorChannelRoomCreateFullRoom",
  "kErrorChannelRoomCreateClientCount",
  "kErrorChannelRoomCreateNoSuchLevel",
  "kErrorChannelOption",
  "kErrorChannelOptionRoomError",
  "kErrorChannelOptionRoomNameInvalid",
  "kErrorChannelOptionLevelIdInvalid",
  "kErrorChannelOptionGameModeInvalid",
  "kErrorChannelOptionNotHost",
  "kErrorChannelOptionRuleValue",
  "kErrorChannelOptionVictoryRule",
  "kErrorChannelOptionGameType",
  "kErrorChannelOptionSpawnTime",
  "kErrorChannelOptionSpecialMode",
  "kErrorChannelOptionDeadViewMode",
  "kErrorChannelOptionNoGroup",
  "kErrorChannelRoomEnter",
  "kErrorChannelRoomEnterRoomError",
  "kErrorChannelRoomEnterJoinOnPlaying",
  "kErrorChannelRoomEnterMemberSize",
  "kErrorChannelRoomEnterEnoughSlots",
  "kErrorChannelRoomEnterPassword",
  "kErrorChannelRoomChangeTeam",
  "kErrorChannelRoomChangeTeamTeamError",
  "kErrorChannelRoomChangeTeamSameTeam",
  "kErrorChannelRoomChangeTeamIdError",
  "kErrorChannelRoomChangeTeamIsReady",
  "kErrorChannelRoomChangeTeamBalance",
  "kErrorChannelChangeSlot",
  "kErrorChannelChangeSlotRoomError",
  "kErrorChannelChangeSlotNotExist",
  "kErrorChannelChangeSlotEqual",
  "kErrorChannelChangeSlotHasClient",
  "kErrorChannelChangeSlotPreserveForOther",
  "kErrorChannelChangeSlotClose",
  "kErrorChannelChangeSlotReady",
  "kErrorChannelChangeSlotBalance",
  "kErrorChannelChangeSlotStatus",
  "kErrorChannelChangeSlotStatusRoomError",
  "kErrorChannelChangeSlotStatusNotHost",
  "kErrorChannelChangeSlotStatusNotExist",
  "kErrorChannelChangeSlotStatusStateError",
  "kErrorChannelChangeSlotStatusEqual",
  "kErrorChannelChangeSlotStatusBalance",
  "kErrorChannelPreserveSlot",
  "kErrorChannelPreserveSlotCannot",
  "kErrorChannelPreserveSlotAlreadyPreserved",
  "kErrorChannelPreserveSlotAlreadyInRoom",
  "kErrorChannelClientReady",
  "kErrorChannelClientReadyAlready",
  "kErrorChannelClientReadyTeam",
  "kErrorChannelClientReadyHost",
  "kErrorChannelClientReadyBalance",
  "kErrorChannelGameStart",
  "kErrorChannelGameStartLevelError",
  "kErrorChannelGameStartBalance",
  "kErrorChannelGameStartGroupMatchNoGroup",
  "kErrorChannelGameStartGroupMatchGroupError",
  "kErrorChannelGameStartGroupMatchGroupEqual",
  "kErrorChannelGameStartGameServerError",
  "kErrorChannelGameEnter",
  "kErrorChannelGameEnterBalance",
  "kErrorChannelGameEnterJoinOnPlaying",
  "kErrorChannelGameEnterJoinPK",
  "kErrorChannelGameEnterRoomIdError",
  "kErrorChannelGameEnterLeaveWhenConnecting",
  "kErrorChannelGameEnterCharacterInfoError",
  "kErrorChannelGameEnterWeaponError",
  "kErrorChannelGameEnterGameEnded",
  "kErrorChannelKickClient",
  "kErrorChannelKickClientNotHost",
  "kErrorChannelKickClientIdError",
  "kErrorChannelKickClientInGame",
  "kErrorChannelRoomInvite",
  "kErrorChannelRoomInviteRoomError",
  "kErrorChannelRoomInviteRoomFull",
  "kErrorChannelRoomInvitePreserveError",
  "kErrorChannelRoomInviteAlreadyPreserved",
  "kErrorChannelRoomInviteAlreadyInRoom"
}
SocialityErrorChat = {
  "kErrorSocialNone",
  "kErrorSocialCharacterIsNotFound",
  "kErrorSocialFriendIsNotFound",
  "kErrorSocialAlreadyIsFriend",
  "kErrorSocialAlreadyIsBlack",
  "kErrorSocialCharacterIsNotOnline",
  "kErrorSocialFriendIsNotOnline",
  "kErrorSocialChatToFast",
  "kErrorSocialExceedMaxGroupLimit",
  "kErrorSocialNoPrivilegeToOperate",
  "kErrorSocialGroupNameIsDuplicate",
  "kErrorSocialGroupIsNotFound",
  "kErrorSocialGroupAddMemberError",
  "kErrorSocialExceedMaxFriendLimit",
  "kErrorSocialExceedMaxBlackLimit",
  "kErrorSocialChannelIsNotFound",
  "kErrorSocialAlreadyInChannel",
  "kErrorSocialAlreadyInGroup",
  "kErrorSocialExceedMaxChannelLimit",
  "kErrorSocialUnknown",
  "kErrorSocialCreateGroupExceedLimit",
  "kErrorSocialExceedGroupMaxMemberLimit",
  "kErrorSocialGroupNameInvalid",
  "kErrorSocialChannelIsFull",
  "C_ErrorParameter"
}
ServerError = CreatEnumTable(ServerError)
ServerErrorProxy = CreatEnumTable(ServerErrorProxy, 10000)
ServerErrorChannel = CreatEnumTable(ServerErrorChannel, 20000)
SocialityErrorChat = CreatEnumTable(SocialityErrorChat, 0)
ErrorText = {
  [ServerError.kErrorNone] = "kErrorNone",
  [ServerErrorProxy.kErrorProxyStart] = "kErrorProxyStart",
  [ServerErrorProxy.kErrorProxyEnterChannel] = "kErrorProxyEnterChannel",
  [ServerErrorProxy.kErrorProxyChannelFull] = "kErrorProxyChannelFull",
  [ServerErrorProxy.kErrorProxyChannelConnect] = "kErrorProxyChannelConnect",
  [ServerErrorProxy.kErrorProxyChannelConnectClientCount] = "kErrorProxyChannelConnectClientCount",
  [ServerErrorProxy.kErrorProxyChannelConnectAlreadyIn] = "kErrorProxyChannelConnectAlreadyIn",
  [ServerErrorProxy.kErrorProxyMatchingFailed] = "kErrorProxyMatchingFailed",
  [ServerErrorProxy.kErrorProxyCancelMatchingFailed] = "kErrorProxyCancelMatchingFailed",
  [ServerErrorProxy.kErrorProxyMatchingFailedServerOffline] = "kErrorProxyMatchingFailedServerOffline",
  [ServerErrorProxy.kErrorProxyTeamMatchingNotLeader] = "team matching not leader",
  [ServerErrorProxy.kErrorProxyTeamMatchingCancelNotLeader] = "team matching cancel not leader",
  [ServerErrorProxy.kErrorProxyTeamCreate] = "kErrorProxyTeamCreate",
  [ServerErrorProxy.kErrorProxyTeamCreateAlreadyHaveTeam] = "kErrorProxyTeamCreateAlreadyHaveTeam",
  [ServerErrorProxy.kErrorProxyTeamCreateLevelError] = "team create level error",
  [ServerErrorProxy.kErrorProxyTeamCreateNoGameMode] = "team create no game mode",
  [ServerErrorProxy.kErrorProxyTeamInvite] = "kErrorProxyTeamInvite",
  [ServerErrorProxy.kErrorProxyTeamInviteSelf] = "kErrorProxyTeamInviteSelf",
  [ServerErrorProxy.kErrorProxyTeamInviteAlreadyInOtherTeam] = "kErrorProxyTeamInviteAlreadyInOtherTeam",
  [ServerErrorProxy.kErrorProxyTeamInviteAlreadyInTeam] = "kErrorProxyTeamInviteAlreadyInTeam",
  [ServerErrorProxy.kErrorProxyTeamInviteClientError] = "kErrorProxyTeamInviteClientError",
  [ServerErrorProxy.kErrorProxyTeamInviteNotTeamLeader] = "kErrorProxyTeamInviteNotTeamLeader",
  [ServerErrorProxy.kErrorProxyTeamInviteTeamFull] = GetUTF8Text("msgbox_common_num_1193"),
  [ServerErrorProxy.kErrorProxyTeamInviteMatching] = GetUTF8Text("msgbox_battlefield_join_late"),
  [ServerErrorProxy.kErrorProxyTeamInviteGameing] = "kErrorProxyTeamInviteGameing",
  [ServerErrorProxy.kErrorProxyTeamInviteLevelError] = "team invite level error",
  [ServerErrorProxy.kErrorProxyTeamJoin] = "kErrorProxyTeamJoin",
  [ServerErrorProxy.kErrorProxyTeamJoinLeaderError] = "kErrorProxyTeamJoinLeaderError",
  [ServerErrorProxy.kErrorProxyTeamJoinLeaderIdError] = "kErrorProxyTeamJoinLeaderIdError",
  [ServerErrorProxy.kErrorProxyTeamJoinMemberError] = "kErrorProxyTeamJoinMemberError",
  [ServerErrorProxy.kErrorProxyTeamJoinTeamFull] = "kErrorProxyTeamJoinTeamFull",
  [ServerErrorProxy.kErrorProxyTeamJoinTeamNotExist] = GetUTF8Text("msgbox_battlefield_Team_disbanned"),
  [ServerErrorProxy.kErrorProxyTeamLeave] = "kErrorProxyTeamLeave",
  [ServerErrorProxy.kErrorProxyTeamLeaveTeamNotExist] = "kErrorProxyTeamLeaveTeamNotExist",
  [ServerErrorProxy.kErrorProxyTeamLeaveTeamNotInTeam] = "kErrorProxyTeamLeaveTeamNotInTeam",
  [ServerErrorProxy.kErrorProxyTeamChangeLeader] = "team change leader",
  [ServerErrorProxy.kErrorProxyTeamChangeLeaderNoTeam] = "team change leader no team",
  [ServerErrorProxy.kErrorProxyTeamChangeLeaderNotLeader] = "team change leader not leader",
  [ServerErrorProxy.kErrorProxyTeamChangeLeaderNotInTeam] = "team change leader not in team",
  [ServerErrorProxy.kErrorProxyTeamChangeGameMode] = "team change game mode",
  [ServerErrorProxy.kErrorProxyTeamChangeGameModeNoTeam] = "team change game mode no team",
  [ServerErrorProxy.kErrorProxyTeamChangeGameModeNotLeader] = "team change game mode not leader",
  [ServerErrorProxy.kErrorProxyTeamChangeGameModeNoMode] = "team change game mode no mode",
  [ServerErrorProxy.kErrorProxyTeamKick] = "team kick",
  [ServerErrorProxy.kErrorProxyTeamKickNoTeam] = "team kick no team",
  [ServerErrorProxy.kErrorProxyTeamKickNotLeader] = "team kick not leader",
  [ServerErrorProxy.kErrorProxyTeamKickNotInTeam] = "team kick not in team",
  [ServerErrorProxy.kErrorProxyTeamKickInGame] = "team kick player in game",
  [ServerErrorProxy.kErrorProxyRoomInvite] = "kErrorProxyRoomInvite",
  [ServerErrorProxy.kErrorProxyRoomInviteSelf] = "kErrorProxyRoomInviteSelf",
  [ServerErrorProxy.kErrorProxyRoomInviteClientError] = "kErrorProxyRoomInviteClientError",
  [ServerErrorProxy.kErrorProxyRoomInviteClientNotInLobby] = "kErrorProxyRoomInviteClientNotInLobby",
  [ServerErrorProxy.kErrorProxyRoomInviteClientInGame] = "kErrorProxyRoomInviteClientInGame",
  [ServerErrorProxy.kErrorProxyRoomInviteNotInRoom] = "kErrorProxyRoomInviteNotInRoom",
  [ServerErrorProxy.kErrorProxyTeamInviteRefused] = "kErrorProxyTeamInviteRefused",
  [ServerErrorProxy.kErrorProxyRoomNameInvalid] = GetUTF8Text("msgbox_common_num_1282"),
  [ServerErrorProxy.kErrorProxyTeamCall] = "kErrorProxyTeamCall",
  [ServerErrorProxy.kErrorProxyGuildInvite] = "kErrorProxyGuildInvite",
  [ServerErrorProxy.kErrorProxyGuildInviteClientError] = "kErrorProxyGuildInviteClientError",
  [ServerErrorProxy.kErrorProxyGuildInviteSelf] = "kErrorProxyGuildInviteSelf",
  [ServerErrorProxy.kErrorProxyGuildInviteClientNotInLobby] = "kErrorProxyGuildInviteClientNotInLobby",
  [ServerErrorProxy.kErrorProxyGuildInviteClientInGame] = "kErrorProxyGuildInviteClientInGame",
  [ServerErrorChannel.kErrorChannelStart] = "channel error start",
  [ServerErrorChannel.kErrorChannelRoomCreate] = GetUTF8Text("msgbox_common_num_1330"),
  [ServerErrorChannel.kErrorChannelRoomCreateFullRoom] = GetUTF8Text("msgbox_common_num_1340"),
  [ServerErrorChannel.kErrorChannelRoomCreateClientCount] = "room create client count error",
  [ServerErrorChannel.kErrorChannelRoomCreateNoSuchLevel] = "room create no such level",
  [ServerErrorChannel.kErrorChannelOption] = "option change error",
  [ServerErrorChannel.kErrorChannelOptionRoomError] = "option change room error",
  [ServerErrorChannel.kErrorChannelOptionRoomNameInvalid] = GetUTF8Text("msgbox_common_num_1282"),
  [ServerErrorChannel.kErrorChannelOptionLevelIdInvalid] = "option change level id invalid",
  [ServerErrorChannel.kErrorChannelOptionGameModeInvalid] = "kErrorChannelOptionGameModeInvalid",
  [ServerErrorChannel.kErrorChannelOptionNotHost] = GetUTF8Text("msgbox_common_num_1391"),
  [ServerErrorChannel.kErrorChannelOptionRuleValue] = "option change rule value error",
  [ServerErrorChannel.kErrorChannelOptionVictoryRule] = GetUTF8Text("msgbox_common_num_1386"),
  [ServerErrorChannel.kErrorChannelOptionGameType] = "\230\184\184\230\136\143\230\168\161\229\188\143\228\184\141\232\131\189\228\191\174\230\148\185",
  [ServerErrorChannel.kErrorChannelOptionSpawnTime] = GetUTF8Text("msgbox_common_num_1308"),
  [ServerErrorChannel.kErrorChannelOptionSpecialMode] = GetUTF8Text("msgbox_common_num_1397"),
  [ServerErrorChannel.kErrorChannelOptionDeadViewMode] = GetUTF8Text("msgbox_common_num_1329"),
  [ServerErrorChannel.kErrorChannelOptionNoGroup] = "\228\184\141\232\131\189\233\128\137\230\139\169\230\136\152\233\152\159\230\136\152",
  [ServerErrorChannel.kErrorChannelRoomEnter] = GetUTF8Text("msgbox_common_num_1382"),
  [ServerErrorChannel.kErrorChannelRoomEnterRoomError] = GetUTF8Text("msgbox_common_num_1336"),
  [ServerErrorChannel.kErrorChannelRoomEnterJoinOnPlaying] = GetUTF8Text("msgbox_common_num_1345"),
  [ServerErrorChannel.kErrorChannelRoomEnterMemberSize] = "room enter member size greater than 4",
  [ServerErrorChannel.kErrorChannelRoomEnterEnoughSlots] = GetUTF8Text("msgbox_common_num_1294"),
  [ServerErrorChannel.kErrorChannelRoomEnterPassword] = GetUTF8Text("msgbox_common_num_1332"),
  [ServerErrorChannel.kErrorChannelRoomChangeTeam] = GetUTF8Text("msgbox_common_num_1343"),
  [ServerErrorChannel.kErrorChannelRoomChangeTeamTeamError] = "room change team team error",
  [ServerErrorChannel.kErrorChannelRoomChangeTeamSameTeam] = GetUTF8Text("msgbox_common_num_1379"),
  [ServerErrorChannel.kErrorChannelRoomChangeTeamIdError] = "room change team team client in room id error",
  [ServerErrorChannel.kErrorChannelRoomChangeTeamIsReady] = GetUTF8Text("msgbox_common_num_1347"),
  [ServerErrorChannel.kErrorChannelRoomChangeTeamBalance] = GetUTF8Text("msgbox_common_num_1344"),
  [ServerErrorChannel.kErrorChannelChangeSlot] = GetUTF8Text("msgbox_common_num_1287"),
  [ServerErrorChannel.kErrorChannelChangeSlotRoomError] = "change slot room error",
  [ServerErrorChannel.kErrorChannelChangeSlotNotExist] = GetUTF8Text("msgbox_common_num_1287"),
  [ServerErrorChannel.kErrorChannelChangeSlotEqual] = GetUTF8Text("msgbox_common_num_1287"),
  [ServerErrorChannel.kErrorChannelChangeSlotHasClient] = GetUTF8Text("msgbox_common_num_1287"),
  [ServerErrorChannel.kErrorChannelChangeSlotPreserveForOther] = GetUTF8Text("msgbox_common_num_1287"),
  [ServerErrorChannel.kErrorChannelChangeSlotClose] = GetUTF8Text("msgbox_common_num_1287"),
  [ServerErrorChannel.kErrorChannelChangeSlotReady] = GetUTF8Text("msgbox_common_num_1287"),
  [ServerErrorChannel.kErrorChannelChangeSlotBalance] = GetUTF8Text("msgbox_common_num_1287"),
  [ServerErrorChannel.kErrorChannelChangeSlotStatus] = GetUTF8Text("msgbox_common_num_1306"),
  [ServerErrorChannel.kErrorChannelChangeSlotStatusRoomError] = GetUTF8Text("msgbox_common_num_1306"),
  [ServerErrorChannel.kErrorChannelChangeSlotStatusNotHost] = GetUTF8Text("msgbox_common_num_1306"),
  [ServerErrorChannel.kErrorChannelChangeSlotStatusNotExist] = GetUTF8Text("msgbox_common_num_1306"),
  [ServerErrorChannel.kErrorChannelChangeSlotStatusStateError] = GetUTF8Text("msgbox_common_num_1306"),
  [ServerErrorChannel.kErrorChannelChangeSlotStatusEqual] = GetUTF8Text("msgbox_common_num_1306"),
  [ServerErrorChannel.kErrorChannelChangeSlotStatusBalance] = GetUTF8Text("msgbox_common_num_1306"),
  [ServerErrorChannel.kErrorChannelPreserveSlot] = "preserve slot error",
  [ServerErrorChannel.kErrorChannelPreserveSlotCannot] = GetUTF8Text("UI_common_Insufficient_slot"),
  [ServerErrorChannel.kErrorChannelPreserveSlotAlreadyPreserved] = GetUTF8Text("msgbox_common_num_1309"),
  [ServerErrorChannel.kErrorChannelPreserveSlotAlreadyInRoom] = GetUTF8Text("msgbox_common_num_1335"),
  [ServerErrorChannel.kErrorChannelClientReady] = GetUTF8Text("msgbox_common_num_1292"),
  [ServerErrorChannel.kErrorChannelClientReadyAlready] = GetUTF8Text("msgbox_common_num_1328"),
  [ServerErrorChannel.kErrorChannelClientReadyTeam] = "client ready team error",
  [ServerErrorChannel.kErrorChannelClientReadyHost] = "client ready client is host",
  [ServerErrorChannel.kErrorChannelClientReadyBalance] = GetUTF8Text("msgbox_common_num_1392"),
  [ServerErrorChannel.kErrorChannelGameStart] = GetUTF8Text("msgbox_common_num_1395"),
  [ServerErrorChannel.kErrorChannelGameStartLevelError] = "game start level error",
  [ServerErrorChannel.kErrorChannelGameStartBalance] = GetUTF8Text("msgbox_common_num_1203"),
  [ServerErrorChannel.kErrorChannelGameStartGroupMatchNoGroup] = "kErrorChannelGameStartGroupMatchNoGroup",
  [ServerErrorChannel.kErrorChannelGameStartGroupMatchGroupError] = "kErrorChannelGameStartGroupMatchGroupError",
  [ServerErrorChannel.kErrorChannelGameStartGroupMatchGroupEqual] = "kErrorChannelGameStartGroupMatchGroupEqual",
  [ServerErrorChannel.kErrorChannelGameStartGameServerError] = "game start game server start error",
  [ServerErrorChannel.kErrorChannelGameEnter] = GetUTF8Text("msgbox_common_num_1320"),
  [ServerErrorChannel.kErrorChannelGameEnterBalance] = GetUTF8Text("msgbox_common_num_1203"),
  [ServerErrorChannel.kErrorChannelGameEnterJoinOnPlaying] = GetUTF8Text("msgbox_common_num_1345"),
  [ServerErrorChannel.kErrorChannelGameEnterJoinPK] = GetUTF8Text("msgbox_common_num_1345"),
  [ServerErrorChannel.kErrorChannelGameEnterRoomIdError] = GetUTF8Text("msgbox_common_num_1336"),
  [ServerErrorChannel.kErrorChannelGameEnterLeaveWhenConnecting] = GetUTF8Text("msgbox_common_num_1298"),
  [ServerErrorChannel.kErrorChannelGameEnterCharacterInfoError] = GetUTF8Text("msgbox_common_num_1371"),
  [ServerErrorChannel.kErrorChannelGameEnterWeaponError] = GetUTF8Text("msgbox_common_num_1190"),
  [ServerErrorChannel.kErrorChannelGameEnterGameEnded] = "game enter game ended",
  [ServerErrorChannel.kErrorChannelKickClient] = "kick client error",
  [ServerErrorChannel.kErrorChannelKickClientNotHost] = "kick client client is not host",
  [ServerErrorChannel.kErrorChannelKickClientIdError] = GetUTF8Text("msgbox_common_num_1331"),
  [ServerErrorChannel.kErrorChannelKickClientInGame] = GetUTF8Text("msgbox_common_num_1205"),
  [ServerErrorChannel.kErrorChannelRoomInvite] = "kErrorChannelRoomInvite",
  [ServerErrorChannel.kErrorChannelRoomInviteRoomError] = "kErrorChannelRoomInviteRoomError",
  [ServerErrorChannel.kErrorChannelRoomInviteRoomFull] = "kErrorChannelRoomInviteRoomFull",
  [ServerErrorChannel.kErrorChannelRoomInvitePreserveError] = "kErrorChannelRoomInvitePreserveError",
  [ServerErrorChannel.kErrorChannelRoomInviteAlreadyPreserved] = "kErrorChannelRoomInviteAlreadyPreserved",
  [ServerErrorChannel.kErrorChannelRoomInviteAlreadyInRoom] = "kErrorChannelRoomInviteAlreadyInRoom"
}
SocialityErrorText = {
  [SocialityErrorChat.kErrorSocialNone] = GetUTF8Text("msgbox_social_additional_string_164"),
  [SocialityErrorChat.kErrorSocialCharacterIsNotFound] = GetUTF8Text("msgbox_common_num_1013"),
  [SocialityErrorChat.kErrorSocialFriendIsNotFound] = GetUTF8Text("msgbox_common_num_1396"),
  [SocialityErrorChat.kErrorSocialAlreadyIsFriend] = GetUTF8Text("msgbox_common_num_1390"),
  [SocialityErrorChat.kErrorSocialAlreadyIsBlack] = GetUTF8Text("msgbox_common_num_1381"),
  [SocialityErrorChat.kErrorSocialCharacterIsNotOnline] = GetUTF8Text("msgbox_common_num_1322"),
  [SocialityErrorChat.kErrorSocialFriendIsNotOnline] = GetUTF8Text("msgbox_common_num_1365"),
  [SocialityErrorChat.kErrorSocialChatToFast] = GetUTF8Text("msgbox_social_additional_string_165"),
  [SocialityErrorChat.kErrorSocialExceedMaxGroupLimit] = GetUTF8Text("msgbox_common_num_1230"),
  [SocialityErrorChat.kErrorSocialNoPrivilegeToOperate] = GetUTF8Text("msgbox_common_num_1383"),
  [SocialityErrorChat.kErrorSocialGroupNameIsDuplicate] = GetUTF8Text("msgbox_common_num_1317"),
  [SocialityErrorChat.kErrorSocialGroupIsNotFound] = GetUTF8Text("msgbox_common_num_1319"),
  [SocialityErrorChat.kErrorSocialGroupAddMemberError] = GetUTF8Text("msgbox_common_num_1349"),
  [SocialityErrorChat.kErrorSocialExceedMaxFriendLimit] = GetUTF8Text("msgbox_common_num_1288"),
  [SocialityErrorChat.kErrorSocialExceedMaxBlackLimit] = GetUTF8Text("msgbox_common_num_1244"),
  [SocialityErrorChat.kErrorSocialChannelIsNotFound] = GetUTF8Text("msgbox_common_num_1337"),
  [SocialityErrorChat.kErrorSocialAlreadyInChannel] = GetUTF8Text("msgbox_common_num_1286"),
  [SocialityErrorChat.kErrorSocialAlreadyInGroup] = GetUTF8Text("msgbox_social_additional_string_166"),
  [SocialityErrorChat.kErrorSocialExceedMaxChannelLimit] = GetUTF8Text("msgbox_common_num_1394"),
  [SocialityErrorChat.kErrorSocialUnknown] = GetUTF8Text("msgbox_common_num_1293"),
  [SocialityErrorChat.kErrorSocialCreateGroupExceedLimit] = GetUTF8Text("msgbox_common_num_1225"),
  [SocialityErrorChat.kErrorSocialExceedGroupMaxMemberLimit] = GetUTF8Text("msgbox_common_num_1232"),
  [SocialityErrorChat.kErrorSocialGroupNameInvalid] = GetUTF8Text("msgbox_social_additional_string_167"),
  [SocialityErrorChat.kErrorSocialChannelIsFull] = GetUTF8Text("msgbox_common_num_1223"),
  [SocialityErrorChat.C_ErrorParameter] = GetUTF8Text("msgbox_common_num_1010")
}
